server {
    listen 80;
    server_name localhost;

    # Serve Angular build files
    root /usr/share/nginx/html;
    index index.html;

    # Let Angular handle routing
    location / {
        try_files $uri /index.html;
        open_file_cache max=1000 inactive=20s;
    }

    # Proxy API calls to Spring Boot backend
    location /api/ {
        proxy_pass http://Backend_Spring;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
